fix anon arg in backup_sleep_without_gvl compiler complain
    database.c: In function 'backup_sleep_without_gvl':
    database.c:425:1: error: parameter name omitted
     void *backup_sleep_without_gvl(void *) {
     ^~~~

as an alternative it can be replaced with accomp attr:

    void *backup_sleep_without_gvl(__attribute__((unused)) void *unused)

Signed-off-by: Ivan Prisyazhnyy <john.koepi@gmail.com>